services:
  mongo1:
    container_name: mongo1
    image: mongo:7.0
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-cluster
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: phuonglv



  mongo2:
    image: mongo:7.0
    container_name: mongo2
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27018:27017
    networks:
      - mongo-cluster
    depends_on:
      - mongo1
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: phuonglv



  mongo3:
    image: mongo:7.0
    container_name: mongo3
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27019:27017
    networks:
      - mongo-cluster
    depends_on:
      - mongo1
      - mongo2
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: phuonglv



volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:

networks:
  mongo-cluster:
    driver:
      bridge
